# Generated by Django 4.0.5 on 2022-06-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0008_rename_author_image_name_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
